routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localize', 'localizationRedirect']], function () use($router) {
    $router->get('/', 'PageController@index')->name('/');
    $router->get('/about', 'PageController@about')->name('about');
    $router->get('/contact-us', 'PageController@contactus')->name('contactus');
    $router->get('/teamus', 'PageController@teams')->name('team');
    $router->get('/search', 'PageController@search')->name('search');

    $router->group(['prefix' => '/services', 'as' => 'services.'], function() use($router) {
        $router->get('/', 'ServiceController@index')->name('index');
        $router->get('/{name}', 'ServiceController@show')->name('show');
    });

    // Posts
    $router->get('/threads', 'ThreadController@index')->name('threads-list');
    $router->get('/threads/{thread}', 'ThreadController@show')->name('thread-show');
    $router->get('/threads/{channel}','ThreadController@index')->name('threads-channel');
    $router->get('/threads/{channel}/{thread}','ThreadController@show')->name('threads-show');
    $router->post('/threads/{thread}/reply', 'ReplyController@store')->name('reply.create');

    // news
    $router->resource('/news', 'NewsController')->only(['index', 'show'])
        ->names([
            'index' =>  'news.index',
            'show'  =>  'news.show'
        ]);

    // Treatments
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/{treatment}', 'TreatmentController@show')->name('show');
        $router->post('/{id}/advice', 'TreatmentController@store_request')->name('advice-request');
    });

    // Conditions
    $router->group(['prefix' => '/conditions', 'as' => 'conditions.'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        $router->get('/{condition}', 'ConditionController@show')->name('show');
    });

    // Doctors
    $router->group(['prefix' => '/doctors', 'as' => 'teams.'], function() use($router) {
        $router->get('/', 'TeamController@index')->name('index');
        $router->get('/{name}', 'TeamController@show')->name('show');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/* start admin routes */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:operator|admin'], 'as' => 'admin.'], function() use($router){
    $router->get('/', 'PanelController@panel')->name('panel');

    $router->resource('/users-opinions', 'UsersOpinionController');

    /* Departments */
    $router->group(['prefix' => '/departments', 'as' => 'departments.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'DepartmentController@index')->name('index');
    });

    /* Services */
    $router->group(['prefix' => 'services-categories', 'as' => 'services-categories.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'ServiceCategoryController@index')->name('index');
        $router->get('/{id}/edit', 'ServiceCategoryController@edit')->name('edit');
        $router->put('/{id}', 'ServiceCategoryController@update')->name('update');
    });

    /* conditions */
    $router->group(['prefix' => 'conditions', 'as' => 'conditions.', 'middleware' => 'role:conditions-manager'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        
        $router->group(['prefix' => '/{id}'], function() use($router){
            $router->put('', 'ConditionController@update')->name('update');
            $router->get('/edit', 'ConditionController@edit')->name('edit');
            $router->get('/faq', 'ConditionController@faq')->name('faq');
            $router->get('/seo', 'ConditionController@seo')->name('seo');
            $router->patch('/seo', 'ConditionController@storeSeo');
        });
    });
    
    /* treatments */
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.', 'middleware' => 'role:treatments-manager'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/treatment-requests', 'TreatmentController@requestList')->name('requests');
        
        $router->group(['prefix' => '/{id}'], function() use($router) {
            $router->put('/', 'TreatmentController@update')->name('update');
            $router->get('/edit', 'TreatmentController@edit')->name('edit');
            $router->get('/faq', 'TreatmentController@faq');
            $router->get('/seo', 'TreatmentController@seo')->name('seo');
            $router->patch('/seo', 'TreatmentController@storeSeo')->name('seo');
            $router->get('/requests', 'TreatmentController@adviseList');

            $router->group(['prefix' => '/comments', 'as' => 'comments.'], function() use($router) {
                $router->get('/', 'TreatmentController@fetchCommentsList')->name('index');
                $router->post('/', 'TreatmentController@storeComment')->name('store');
                $router->post('/{comment_id}/edit', 'TreatmentController@updateComment')->name('update');
                $router->get('/create', 'TreatmentController@createComment')->name('create');
                $router->get('/{comment_id}/edit', 'TreatmentController@editComment')->name('edit');
                $router->delete('{comment_id}', 'TreatmentController@destroyComment')->name('delete');
            });


            $router->get('/pricing', 'TreatmentController@pricing')->name('pricing');
        });
    });

    $router->group(['prefix' => '/news', 'as' => 'news.'], function() use($router) {
        $router->get('/', 'NewsController@index')->name('index');
        $router->get('/create', 'NewsController@create')->name('create');
        $router->post('/', 'NewsController@store')->name('store');
        $router->put('/{id}', 'NewsController@update')->name('update');
        $router->get('/{id}/edit', 'NewsController@edit')->name('edit');
        $router->delete('/{id}', 'NewsController@destroy')->name('delete');
    });

    /* Settings */
    $router->group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'SettingController@index')->name('index');
        $router->post('/', 'SettingController@store_setting')->name('store-setting');
        $router->get('/social', 'SettingController@social')->name('social');
        $router->post('/social', 'SettingController@store_social')->name('store-social');
        $router->get('/home_slider', 'PageController@home_main_slider')->name('home-main-slider');
        $router->post('/home_slider', 'PageController@store_main_slider')->name('store-main-slider');
        $router->put('/home_slider', 'PageController@update_main_slider')->name('update-main-slider');
        
        $router->get('/welcome', 'PageController@welcome_page')->name('welcome-page');
        
        // menu
        $router->get('/menu', 'PageController@menu')->name('menu');
        
        // banner
        $router->get('/banner', 'PageController@banner')->name('banner');
        $router->post('/banner', 'PageController@storeBanner')->name('store_banner');

        // about page
        $router->get('/about', 'SettingController@about')->name('about-page');
        $router->post('/about', 'SettingController@storeAbout');
    });

    /* tags */
    $router->group(['prefix' => 'tags', 'as' => 'tags.'], function() use($router) {
        $router->get('/', 'TagController@list')->name('index');
    });

    /* Media */
    $router->group(['prefix' => 'media', 'as' => 'media.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'MediaController@index')->name('index');
        $router->post('/', 'MediaController@store')->name('store');
    });

    /* Employyers */
    $router->group(['prefix' => 'emplyees', 'as' => 'employees.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'EmployeeController@index')->name('index');
    });
    
    // Blog
    $router->group(['prefix' => '/channels', 'as' => 'channels.', 'middleware' => 'role:content-manager'], function() use($router){
        $router->get('/', 'ChannelController@index')->name('index');

        $router->group(['prefix' => '/{id}', 'as' => 'threads.'],function() use($router){
            $router->get('/threads', 'ThreadsController@index')->name('index');
            $router->get('/threads/create', 'ThreadsController@create')->name('create');
            $router->post('/threads', 'ThreadsController@store')->name('store');
            $router->get('/threads/{thread}/seo', 'ThreadsController@seo')->name('seo');
            $router->patch('/threads/{thread}/seo', 'ThreadsController@storeSeo');
            $router->get('/threads/{thread}/edit', 'ThreadsController@edit')->name('edit');
            $router->get('/threads/{thread}/replies', 'ThreadsController@replies')->name('replies');
            $router->put('/threads/{thread}', 'ThreadsController@update')->name('update');
        });
    });

    $router->get('/replies', 'ReplyController@index')->name('replies');
    $router->post('/replies/{reply}', 'ReplyController@store')->name('replies.store');
    $router->delete('/replies/{reply}', 'ReplyController@destroy')->name('replies.delete');

    // Users
    $router->resource('/users', 'UserController')->names([

app/Http/Controllers/Admin/ConditionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Conditions;
use App\Models\Questions;
use App\Http\Controllers\Controller;
use App\Http\Resources\ConditionsResource;
use App\Http\Resources\QuestionsResource;

class ConditionController extends Controller
{
    public function index()
    {
        return view('admin.conditions.index');
    }

    public function list(Request $request)
    {
        $query = Conditions::orderBy('lang', 'desc')->orderBy('id', 'desc');

        if($request->has('lang'))
            $query->where('lang', strtoupper($request->lang));
        
        return ConditionsResource::collection($query->get());
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  =>  'required',
            'parent_id' =>  'sometimes|exists:treatments,id',
            'lang'  =>  'required|in:fa,en,ar',
            'is_published'  =>  'required|boolean'
        ]);

        $condition = Conditions::create([
            'name'      =>  $request->name,
            'parent_id' =>  $request->has('parent_id') ? $request->parent_id : 0,
            'slug'      =>  preg_replace('/(\s+)/', '-', $request->name),
            'lang'      =>  strtoupper($request->lang),
            'is_published'  =>  $request->is_published
        ]);

        return new ConditionsResource($condition);
    }

    public function edit($id){
        if($condition = Conditions::find($id)){
            $conditions = Conditions::select('id', 'name', 'lang')
                ->where('parent_id', 0)
                ->where('lang', strtoupper($condition->lang))
                ->where('id', '!=', $id)
                ->get();


            return view('admin.conditions.edit', compact('condition', 'conditions'));
        }
        else
            abort(404);
    }

    public function update(Request $request, $id){
        $this->validate($request, [
            'name'  =>  'required',
            'parent_id' =>  'nullable',
            'body'  =>  'required'
        ]);

        if($condition = Conditions::find($id)){
            $condition->name = $request->name;
            $condition->slug = preg_replace('/(\s+)/', '-', $request->name);
            $condition->parent_id = $request->parent_id;
            $condition->body = $request->body;
            $condition->reason_title = $request->reason_title;
            $condition->reason_description = $request->reason_description;
            $condition->signs_title = $request->signs_title;
            $condition->signs_description = $request->signs_description;
            $condition->approach_title = $request->approach_title;
            $condition->approach_description = $request->approach_description;

            if($request->hasFile('cover')){
                $condition->cover = $request->file('cover')->extension();
                $request->file('cover')->storeAs('conditions_cover', $condition->id.'.'.$request->file('cover')->extension(), 'public');
            }
    
            if($request->hasFile('page_cover')){
                $condition->poster = $request->file('page_cover')->extension();
                $request->file('page_cover')->storeAs('conditions_poster', $condition->id.'.'.$request->file('page_cover')->extension(), 'public');
            }

            $condition->save();
            return back()->with('success', 'اطلاعات با موفقیت ذخیره گردید');
        }

        abort(404);
    }

    public function changeStatus(Request $request, $id){
        if($condition = Conditions::find($id)){
            $condition->is_published = $request->is_published;
            $condition->save();
        }else
            abort(404);
    }

    public function destroy($id){
        Conditions::where('id', $id)->delete();
    }

    public function seo($id)
    {
        $condition = Conditions::where('id', $id)->first();

        return view('admin.conditions.seo', compact('condition'));
    }

    public function storeSeo(Request $request, $id)
    {
        Conditions::where('id', $id)->update([
            'seo' => json_encode([
                'title' => $request->title,
                'description' => $request->description,
                'keywords'  =>  $request->keywords
            ])
        ]);

        return back()->with('success', 'اطلاعات با موفقیت ذخیره گردید');
    }

    public function faq($id){
        $condition = Conditions::find($id);
        
        return view('admin.conditions.faq', compact('condition'));
    }

    public function faq_list($id){
        $condition = Conditions::with('questions')->find($id);

        return QuestionsResource::collection($condition->questions);
    }

    public function store_faq(Request $request, $id){
        $this->validate($request, [
            'title' =>  'required',
            'description'   =>  'required'
        ]);

        if($condition = Conditions::find($id)){
            $question = $condition->questions()->create([
                'title' => $request->title,
                'description'   =>  $request->description
            ]);
            
            return new QuestionsResource($question);
        }else{
            abort(404);
        }

    }

    public function update_faq(Request $request, $id, $question_id){
        $this->validate($request, [
            'title' =>  'required',
            'description'   =>  'required'
        ]);

        if($condition = Conditions::find($id)){
            $condition->questions()->where('questions_id', $question_id)->update([
                'title' => $request->title,
                'description'   =>  $request->description
            ]);
        }else{
            abort(404);
        }
    }

    public function destroy_faq($id, $question_id){
        if($condition = Conditions::find($id)){
            $condition->questions()->detach($question_id);

            Questions::where('id', $question_id)->delete();
        }else{
            abort(404);
        }
    }
}

app/Http/Controllers/ConditionController.php
<?php

namespace App\Http\Controllers;

use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Http\Request;
use App\Models\Conditions;
use App\Models\Settings;

class ConditionController extends Controller
{
    public function index(Request $request){
        $query = Conditions::where('lang', strtoupper(\LaravelLocalization::getCurrentLocale()))
            ->orderBy('created_at', 'desc')
            ->published();

        $condition = null;

        if($request->condition) {
            $query->where('parent_id', $request->condition);
            $condition = Conditions::find($request->condition);
        }
        
        $conditions = $query->paginate(20);

        SEOMeta::setTitle(\Lang::get('message.pages.conditions'));
        $setting = new Settings;

        return view('conditions.index', compact('conditions', 'condition', 'setting'));
    }

    public function show($id){
        $condition = Conditions::where('id', $id)->published()->with('questions', 'childs', 'parent')->first();

        if($condition){
            if($condition->seo)
                SEOMeta::setTitle($condition->seo->title)->setDescription($condition->seo->description)->setKeywords($condition->seo->keywords);
            else
                SEOMeta::setTitle($condition->name);
            return view('conditions.show', compact('condition'));
        }

        abort(404);
    }
}

resources/views/admin/conditions/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        {{ Breadcrumbs::render('admin-condition', $condition) }}
    </div>

    <div class="container">
        <div class="card text-right">
            <div class="card-header">
                ویرایش {{ $condition->name }}
            </div>

            <div class="card-body">
                <form action="{{ route('admin.conditions.update', ['id' => $condition->id]) }}" method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="name">نام</label>
                                <input type="text" name="name" class="form-control" value="{{ $condition->name }}">
                                @error('name')
                                    <span class="text-danger">{{$message}}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="parent_id">درمان اصلی</label>
                                <select name="parent_id" id="parent_id" class="custom-select">
                                    <option value="0">هیچکدام</option>
                                    @foreach ($conditions as $item)
                                        <option value="{{ $item->id }}" {{ $item->id == $condition->parent_id ? 'selected' : null }}>{{ $item->name }}</option>
                                    @endforeach
                                </select>
                                @error('parent_id')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="custom-file">
                                <input type="file" name="cover" class="custom-file-input" id="cover" value="کاور" onchange="prograssBar(this)">
                                <label class="custom-file-label text-left cover" for="cover">انتخاب کاور</label>
                                <small>سایز فایل: ۴۴۲*۶۰۵</small>
                            </div>
    
                            <img src="{{ $condition->cover }}" alt="تصویر کوچک" class="img-thumbnail" style="height:250px">
                        </div>
    
                        <div class="col-md-6">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" name="page_cover" id="page_cover" value="عکس بالای صفحه" onchange="prograssBar(this)">
                                <label class="custom-file-label text-left page_cover" for="page_cover">کاور صفحه</label>
                                <small>سایز فایل: ۹۹۵*۱۹۲۰</small>
                            </div>
    
                            <img src="{{ $condition->poster }}" alt="تصویر کوچک" class="img-thumbnail" style="height:250px">
                        </div>

                        <div class="col-md-12 mt-4">
                            <div class="form-group">
                                <label for="body">توضیحات</label>
                                <textarea class="form-control body" name="body">{{ $condition->body }}</textarea>
                                @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12 mt-4">
                            <div class="form-group">
                                <label for="" class="h3">علت ایجاد</label>
                                <input type="text" class="form-control" name="reason_title" value="{{ $condition->reason_title }}">
                            </div>

                            <div class="form-group">
                                <label for="body">توضیحات</label>
                                <textarea class="form-control body" name="reason_description">{{ $condition->reason_description }}</textarea>
                                @error('reason_description')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12 mt-4">
                            <div class="form-group">
                                <label for="" class="h3">علائم</label>
                                <input type="text" class="form-control" name="signs_title" value="{{ $condition->signs_title }}">
                            </div>

                            <div class="form-group">
                                <label for="body">توضیحات</label>
                                <textarea class="form-control body" name="signs_description">{{ $condition->signs_description }}</textarea>
                                @error('signs_description')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12 mt-4">
                            <div class="form-group">
                                <label for="" class="h3">راهکار های درمان</label>
                                <input type="text" class="form-control" name="approach_title" value="{{ $condition->approach_title }}">
                            </div>

                            <div class="form-group">
                                <label for="body">توضیحات</label>
                                <textarea class="form-control body" name="approach_description">{{ $condition->approach_description }}</textarea>
                                @error('approach_description')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12">
                            <input type="submit" id="submit" class="btn btn-primary" value="ذخیره">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('js')
<script src="https://cdn.tiny.cloud/1/xv3yszddrqi786uyfpl0vjjrgokm86a719783eo4weku3u6k/tinymce/5/tinymce.min.js"></script>
    <script src="{{ mix('assets/js/admin/create_thread.js') }}"></script>
@endpush

resources/views/admin/conditions/faq.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        {{ Breadcrumbs::render('admin-condition-faq', $condition) }}
    </div>

    <div class="container" id="faq_container" data-type="conditions" data-id="{{ $condition->id }}"></div>
@endsection

@push('js')
    <script src={{ mix('assets/js/admin/faq.js') }}></script>
@endpush

resources/views/admin/conditions/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        {{ Breadcrumbs::render('admin-conditions-list') }}
    </div>

    <div class="container" id="conditions_container"></div>
@endsection


@push('js')
    <script src={{ mix('assets/js/admin/conditions.js') }}></script>
@endpush

resources/views/admin/conditions/seo.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
    {{ Breadcrumbs::render('admin-condition-seo', $condition) }}
    </div>
    
    <div class="container">
        <div class="card-body text-right bg-light">
            <form method="post" enctype="multipart/form-data" action="{{ route('admin.conditions.seo', $condition->id) }}">
                @csrf
                @method('PATCH')
                
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="title">عنوان</label>
                            <input type="text" class="form-control" name="title" value="{{ $condition->seo ? $condition->seo->title : old('title') }}">
                        </div>
                    </div>  

                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="title">کلمات کلیدی</label>
                            <input type="text" class="form-control" name="keywords" value="{{ $condition->seo ? $condition->seo->keywords : old('keywords') }}">
                        </div>
                    </div>  

                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="title">توضیحات</label>
                            <input type="text" class="form-control" name="description" value="{{ $condition->seo ? $condition->seo->description : old('description') }}">
                        </div>
                    </div>

                    <div class="col-md-12 mt-3">
                        <button class="btn btn-success" type="submit" id="submit">
                            ذخیره
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection