routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localize', 'localizationRedirect']], function () use($router) {
    $router->get('/', 'PageController@index')->name('/');
    $router->get('/about', 'PageController@about')->name('about');
    $router->get('/contact-us', 'PageController@contactus')->name('contactus');
    $router->get('/teamus', 'PageController@teams')->name('team');
    $router->get('/search', 'PageController@search')->name('search');

    $router->group(['prefix' => '/services', 'as' => 'services.'], function() use($router) {
        $router->get('/', 'ServiceController@index')->name('index');
        $router->get('/{name}', 'ServiceController@show')->name('show');
    });

    // Posts
    $router->get('/threads', 'ThreadController@index')->name('threads-list');
    $router->get('/threads/{thread}', 'ThreadController@show')->name('thread-show');
    $router->get('/threads/{channel}','ThreadController@index')->name('threads-channel');
    $router->get('/threads/{channel}/{thread}','ThreadController@show')->name('threads-show');
    $router->post('/threads/{thread}/reply', 'ReplyController@store')->name('reply.create');

    // news
    $router->resource('/news', 'NewsController')->only(['index', 'show'])
        ->names([
            'index' =>  'news.index',
            'show'  =>  'news.show'
        ]);

    // Treatments
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/{treatment}', 'TreatmentController@show')->name('show');
        $router->post('/{id}/advice', 'TreatmentController@store_request')->name('advice-request');
    });

    // Conditions
    $router->group(['prefix' => '/conditions', 'as' => 'conditions.'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        $router->get('/{condition}', 'ConditionController@show')->name('show');
    });

    // Doctors
    $router->group(['prefix' => '/doctors', 'as' => 'teams.'], function() use($router) {
        $router->get('/', 'TeamController@index')->name('index');
        $router->get('/{name}', 'TeamController@show')->name('show');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/* start admin routes */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:operator|admin'], 'as' => 'admin.'], function() use($router){
    $router->get('/', 'PanelController@panel')->name('panel');

    $router->resource('/users-opinions', 'UsersOpinionController');

    /* Departments */
    $router->group(['prefix' => '/departments', 'as' => 'departments.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'DepartmentController@index')->name('index');
    });

    /* Services */
    $router->group(['prefix' => 'services-categories', 'as' => 'services-categories.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'ServiceCategoryController@index')->name('index');
        $router->get('/{id}/edit', 'ServiceCategoryController@edit')->name('edit');
        $router->put('/{id}', 'ServiceCategoryController@update')->name('update');
    });

    /* conditions */
    $router->group(['prefix' => 'conditions', 'as' => 'conditions.', 'middleware' => 'role:conditions-manager'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        
        $router->group(['prefix' => '/{id}'], function() use($router){
            $router->put('', 'ConditionController@update')->name('update');
            $router->get('/edit', 'ConditionController@edit')->name('edit');
            $router->get('/faq', 'ConditionController@faq')->name('faq');
            $router->get('/seo', 'ConditionController@seo')->name('seo');
            $router->patch('/seo', 'ConditionController@storeSeo');
        });
    });
    
    /* treatments */
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.', 'middleware' => 'role:treatments-manager'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/treatment-requests', 'TreatmentController@requestList')->name('requests');
        
        $router->group(['prefix' => '/{id}'], function() use($router) {
            $router->put('/', 'TreatmentController@update')->name('update');
            $router->get('/edit', 'TreatmentController@edit')->name('edit');
            $router->get('/faq', 'TreatmentController@faq');
            $router->get('/seo', 'TreatmentController@seo')->name('seo');
            $router->patch('/seo', 'TreatmentController@storeSeo')->name('seo');
            $router->get('/requests', 'TreatmentController@adviseList');

            $router->group(['prefix' => '/comments', 'as' => 'comments.'], function() use($router) {
                $router->get('/', 'TreatmentController@fetchCommentsList')->name('index');
                $router->post('/', 'TreatmentController@storeComment')->name('store');
                $router->post('/{comment_id}/edit', 'TreatmentController@updateComment')->name('update');
                $router->get('/create', 'TreatmentController@createComment')->name('create');
                $router->get('/{comment_id}/edit', 'TreatmentController@editComment')->name('edit');
                $router->delete('{comment_id}', 'TreatmentController@destroyComment')->name('delete');
            });


            $router->get('/pricing', 'TreatmentController@pricing')->name('pricing');
        });
    });

    $router->group(['prefix' => '/news', 'as' => 'news.'], function() use($router) {
        $router->get('/', 'NewsController@index')->name('index');
        $router->get('/create', 'NewsController@create')->name('create');
        $router->post('/', 'NewsController@store')->name('store');
        $router->put('/{id}', 'NewsController@update')->name('update');
        $router->get('/{id}/edit', 'NewsController@edit')->name('edit');
        $router->delete('/{id}', 'NewsController@destroy')->name('delete');
    });

    /* Settings */
    $router->group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'SettingController@index')->name('index');
        $router->post('/', 'SettingController@store_setting')->name('store-setting');
        $router->get('/social', 'SettingController@social')->name('social');
        $router->post('/social', 'SettingController@store_social')->name('store-social');
        $router->get('/home_slider', 'PageController@home_main_slider')->name('home-main-slider');
        $router->post('/home_slider', 'PageController@store_main_slider')->name('store-main-slider');
        $router->put('/home_slider', 'PageController@update_main_slider')->name('update-main-slider');
        
        $router->get('/welcome', 'PageController@welcome_page')->name('welcome-page');
        
        // menu
        $router->get('/menu', 'PageController@menu')->name('menu');
        
        // banner
        $router->get('/banner', 'PageController@banner')->name('banner');
        $router->post('/banner', 'PageController@storeBanner')->name('store_banner');

        // about page
        $router->get('/about', 'SettingController@about')->name('about-page');
        $router->post('/about', 'SettingController@storeAbout');
    });

    /* tags */
    $router->group(['prefix' => 'tags', 'as' => 'tags.'], function() use($router) {
        $router->get('/', 'TagController@list')->name('index');
    });

    /* Media */
    $router->group(['prefix' => 'media', 'as' => 'media.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'MediaController@index')->name('index');
        $router->post('/', 'MediaController@store')->name('store');
    });

    /* Employyers */
    $router->group(['prefix' => 'emplyees', 'as' => 'employees.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'EmployeeController@index')->name('index');
    });
    
    // Blog
    $router->group(['prefix' => '/channels', 'as' => 'channels.', 'middleware' => 'role:content-manager'], function() use($router){
        $router->get('/', 'ChannelController@index')->name('index');

        $router->group(['prefix' => '/{id}', 'as' => 'threads.'],function() use($router){
            $router->get('/threads', 'ThreadsController@index')->name('index');
            $router->get('/threads/create', 'ThreadsController@create')->name('create');
            $router->post('/threads', 'ThreadsController@store')->name('store');
            $router->get('/threads/{thread}/seo', 'ThreadsController@seo')->name('seo');
            $router->patch('/threads/{thread}/seo', 'ThreadsController@storeSeo');
            $router->get('/threads/{thread}/edit', 'ThreadsController@edit')->name('edit');
            $router->get('/threads/{thread}/replies', 'ThreadsController@replies')->name('replies');
            $router->put('/threads/{thread}', 'ThreadsController@update')->name('update');
        });
    });

    $router->get('/replies', 'ReplyController@index')->name('replies');
    $router->post('/replies/{reply}', 'ReplyController@store')->name('replies.store');
    $router->delete('/replies/{reply}', 'ReplyController@destroy')->name('replies.delete');

    // Users
    $router->resource('/users', 'UserController')->names([

app/Models/Settings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Settings extends Model
{
    protected $fillable = [
        'name',
        'lang',
        'values'
    ];

    // protected $primaryKey = 'name';

    public function getValuesAttribute(){
        return json_decode($this->attributes['values']) == null ? $this->attributes['values'] : json_decode($this->attributes['values']);
    }

    public function getPostsBannerAttribute()
    {
        return Storage::disk('public')->url('irsa/posts.jpg');
    }

    public function getconditionsBannerAttribute()
    {
        return Storage::disk('public')->url('irsa/conditions.jpg');
    }

    public function getTreatmentsBannerAttribute()
    {
        return Storage::disk('public')->url('irsa/treatments.jpg');
    }

    public function getTeamBannerAttribute()
    {
        return Storage::disk('public')->url('irsa/team.jpg');
    }

    public function getServicesBannerAttribute()
    {
        return Storage::disk('public')->url('irsa/services.jpg');
    }
}

resources/views/pages/about.blade.php
@extends('layouts.app')

@section('body')
<!-- Home Design Inner Pages -->
<div class="ulockd-inner-home">
    <div class="container text-center">
        <div class="row">
            <div class="inner-conraimer-details">
                <div class="col-md-12">
                    <h1 class="text-uppercase">@lang('message.pages.about')</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Home Design Inner Pages -->
<div class="ulockd-inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-icd-layer">
                    <ul class="list-inline ulockd-icd-sub-menu">
                        <li><a href="{{ route('/') }}"> @lang('message.pages.home') </a></li>
                        <li><a href="#"> > </a></li>
                        <li> <a href="{{ route('about') }}"> @lang('message.pages.about') </a> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Our About -->
<section class="ulockd-about2">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="ulock-about">
                    <h1 class="title-bottom ulockd-mrgn630"> @lang('message.welcome.about') <span class="text-thm2"> @lang('message.app') </span></h1>
                </div>

                @if($about)
                    {!! $about->values !!}    
                @endif
            </div>

            <div class="col-sm-12 col-md-5">
                <div class="ulockd-about-box ulockd-mrgn1260">
                    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/pages/contactus.blade.php
@extends('layouts.app')

@section('body')
<!-- Home Design Inner Pages -->
<div class="ulockd-inner-home">
    <div class="container text-center">
        <div class="row">
            <div class="inner-conraimer-details">
                <div class="col-md-12">
                    <h1 class="text-uppercase">@lang('message.pages.contact')</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Home Design Inner Pages -->
<div class="ulockd-inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-icd-layer">
                    <ul class="list-inline ulockd-icd-sub-menu">
                        <li><a href="{{ route('/') }}"> @lang('message.pages.home') </a></li>
                        <li><a href="#"> > </a></li>
                        <li> <a href="{{ route('contactus') }}"> @lang('message.pages.contact') </a> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inner Pages Main Section -->
<section class="ulockd-contact-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <div class="ulockd-cp-title">
                    <h2 class="text-uppercase">@lang('message.pages.contact')</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="contact-info">
                    <div class="contact-details one">
                        <ul class="contact-place one">
                            <li>
                                <span class="flaticon-black-back-closed-envelope-shape"> 
                                    <small>
                                        <i class="fa fa-envelope"></i>
                                        {{ $setting->values->email }}
                                    </small>
                                </span>
                            </li>
                            
                            <li>
                                <span class="flaticon-old-handphone"> 
                                    <i class="fa fa-phone"></i>
                                    <small> {{ $setting->values->phone }} </small>
                                </span>
                            </li>

                            <li>
                                <span class="flaticon-map-marker"> 
                                    <i class="fa fa-map-marker"></i>
                                    <small>{{ $setting->values->address }}</small>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="ulockd-contact-form">
                    <form id="contact_form" name="contact_form" class="contact-form" action="includes/contact.php" method="post" novalidate="novalidate">
                        <div class="messages"></div>

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <input id="form_name" name="form_name" class="form-control ulockd-form-fg required" placeholder="@lang('message.input.name')" type="text">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <input id="form_email" name="form_email" class="form-control ulockd-form-fg required email" placeholder="@lang('message.input.email')" type="email">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <input id="form_phone" name="form_phone" class="form-control ulockd-form-fg required" placeholder="@lang('message.input.phone')" type="text">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    <input id="form_subject" name="form_subject" class="form-control ulockd-form-fg required" placeholder="Subject" type="text">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <textarea id="form_message" name="form_message" class="form-control ulockd-form-tb required" rows="12" placeholder="@lang('message.input.message')"></textarea>
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group ulockd-contact-btn">
                                    <input id="form_botcheck" name="form_botcheck" class="form-control" value="" type="hidden">
                                    <button type="submit" class="btn btn-default ulockd-btn-thm2" data-loading-text="Getting Few Sec...">@lang('message.send')</button>
                                </div>
                            </div> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid ulockd-padz">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-google-map">
                    <div class="" id="map-location" style="height: 312px;"></div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/pages/search.blade.php
@extends('layouts.app')

@section('body')
<!-- Home Design Inner Pages -->
<div class="ulockd-inner-home">
    <div class="container text-center">
        <div class="row">
            <div class="inner-conraimer-details">
                <div class="col-md-12">
                    <h1 class="text-uppercase">@lang('message.search')</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Home Design Inner Pages -->
<div class="ulockd-inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-icd-layer">
                    <ul class="list-inline ulockd-icd-sub-menu">
                        <li><a href="{{ route('/') }}"> @lang('message.pages.home') </a></li>
                        <li><a href="#"> > </a></li>
                        <li> <a href="{{ route('search') }}"> @lang('message.search') </a> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inner Pages Main Section -->
<section class="ulockd-contact-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <div class="ulockd-cp-title">
                    <h2 class="text-uppercase">@lang('message.search')</h2>
                </div>
            </div>
        </div>

        <div class="row">
            @if($data->count())
            @foreach ($data as $item)
            <div class="col-md-12 ulockd-mrgn620">
                @component('components.search_item', ['item' => $item])
                @endcomponent
            </div>
            @endforeach
            @else
            <div class="alert h2 text-center">
                {{ __('message.notfound') }}
            </div>
            @endif

            {{ $data->appends(['q' => request()->q])->links() }}
        </div>
    </div>
</section>
@endsection

resources/views/pages/team.blade.php
@extends('layouts.app')

@section('body')
<!-- Home Design Inner Pages -->
<div class="ulockd-inner-home" style="background-image: url({{ $setting->team_banner }})">
    <div class="container text-center">
        <div class="row">
            <div class="inner-conraimer-details">
                <div class="col-md-12">
                    <h1 class="text-uppercase">@lang('message.welcome.team')</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Home Design Inner Pages -->
<div class="ulockd-inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-icd-layer" dir="{{ LaravelLocalization::getCurrentLocaleDirection() }}">
                    {{ Breadcrumbs::render('teamus') }}
                </div>
            </div>
        </div>
    </div>
</div>

<section class="ulockd-team">
    <div class="container">
        @if ($teams->count())
        <div class="row">
            @foreach ($teams as $team)
                @include('components.teams.team', ['team' => $team, 'size' => 'col-md-4'])
            @endforeach
        </div>
        @endif
    </div>
</section>
@endsection