routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localize', 'localizationRedirect']], function () use($router) {
    $router->get('/', 'PageController@index')->name('/');
    $router->get('/about', 'PageController@about')->name('about');
    $router->get('/contact-us', 'PageController@contactus')->name('contactus');
    $router->get('/teamus', 'PageController@teams')->name('team');
    $router->get('/search', 'PageController@search')->name('search');

    $router->group(['prefix' => '/services', 'as' => 'services.'], function() use($router) {
        $router->get('/', 'ServiceController@index')->name('index');
        $router->get('/{name}', 'ServiceController@show')->name('show');
    });

    // Posts
    $router->get('/threads', 'ThreadController@index')->name('threads-list');
    $router->get('/threads/{thread}', 'ThreadController@show')->name('thread-show');
    $router->get('/threads/{channel}','ThreadController@index')->name('threads-channel');
    $router->get('/threads/{channel}/{thread}','ThreadController@show')->name('threads-show');
    $router->post('/threads/{thread}/reply', 'ReplyController@store')->name('reply.create');

    // news
    $router->resource('/news', 'NewsController')->only(['index', 'show'])
        ->names([
            'index' =>  'news.index',
            'show'  =>  'news.show'
        ]);

    // Treatments
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/{treatment}', 'TreatmentController@show')->name('show');
        $router->post('/{id}/advice', 'TreatmentController@store_request')->name('advice-request');
    });

    // Conditions
    $router->group(['prefix' => '/conditions', 'as' => 'conditions.'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        $router->get('/{condition}', 'ConditionController@show')->name('show');
    });

    // Doctors
    $router->group(['prefix' => '/doctors', 'as' => 'teams.'], function() use($router) {
        $router->get('/', 'TeamController@index')->name('index');
        $router->get('/{name}', 'TeamController@show')->name('show');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/* start admin routes */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:operator|admin'], 'as' => 'admin.'], function() use($router){
    $router->get('/', 'PanelController@panel')->name('panel');

    $router->resource('/users-opinions', 'UsersOpinionController');

    /* Departments */
    $router->group(['prefix' => '/departments', 'as' => 'departments.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'DepartmentController@index')->name('index');
    });

    /* Services */
    $router->group(['prefix' => 'services-categories', 'as' => 'services-categories.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'ServiceCategoryController@index')->name('index');
        $router->get('/{id}/edit', 'ServiceCategoryController@edit')->name('edit');
        $router->put('/{id}', 'ServiceCategoryController@update')->name('update');
    });

    /* conditions */
    $router->group(['prefix' => 'conditions', 'as' => 'conditions.', 'middleware' => 'role:conditions-manager'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        
        $router->group(['prefix' => '/{id}'], function() use($router){
            $router->put('', 'ConditionController@update')->name('update');
            $router->get('/edit', 'ConditionController@edit')->name('edit');
            $router->get('/faq', 'ConditionController@faq')->name('faq');
            $router->get('/seo', 'ConditionController@seo')->name('seo');
            $router->patch('/seo', 'ConditionController@storeSeo');
        });
    });
    
    /* treatments */
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.', 'middleware' => 'role:treatments-manager'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/treatment-requests', 'TreatmentController@requestList')->name('requests');
        
        $router->group(['prefix' => '/{id}'], function() use($router) {
            $router->put('/', 'TreatmentController@update')->name('update');
            $router->get('/edit', 'TreatmentController@edit')->name('edit');
            $router->get('/faq', 'TreatmentController@faq');
            $router->get('/seo', 'TreatmentController@seo')->name('seo');
            $router->patch('/seo', 'TreatmentController@storeSeo')->name('seo');
            $router->get('/requests', 'TreatmentController@adviseList');

            $router->group(['prefix' => '/comments', 'as' => 'comments.'], function() use($router) {
                $router->get('/', 'TreatmentController@fetchCommentsList')->name('index');
                $router->post('/', 'TreatmentController@storeComment')->name('store');
                $router->post('/{comment_id}/edit', 'TreatmentController@updateComment')->name('update');
                $router->get('/create', 'TreatmentController@createComment')->name('create');
                $router->get('/{comment_id}/edit', 'TreatmentController@editComment')->name('edit');
                $router->delete('{comment_id}', 'TreatmentController@destroyComment')->name('delete');
            });


            $router->get('/pricing', 'TreatmentController@pricing')->name('pricing');
        });
    });

    $router->group(['prefix' => '/news', 'as' => 'news.'], function() use($router) {
        $router->get('/', 'NewsController@index')->name('index');
        $router->get('/create', 'NewsController@create')->name('create');
        $router->post('/', 'NewsController@store')->name('store');
        $router->put('/{id}', 'NewsController@update')->name('update');
        $router->get('/{id}/edit', 'NewsController@edit')->name('edit');
        $router->delete('/{id}', 'NewsController@destroy')->name('delete');
    });

    /* Settings */
    $router->group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'SettingController@index')->name('index');
        $router->post('/', 'SettingController@store_setting')->name('store-setting');
        $router->get('/social', 'SettingController@social')->name('social');
        $router->post('/social', 'SettingController@store_social')->name('store-social');
        $router->get('/home_slider', 'PageController@home_main_slider')->name('home-main-slider');
        $router->post('/home_slider', 'PageController@store_main_slider')->name('store-main-slider');
        $router->put('/home_slider', 'PageController@update_main_slider')->name('update-main-slider');
        
        $router->get('/welcome', 'PageController@welcome_page')->name('welcome-page');
        
        // menu
        $router->get('/menu', 'PageController@menu')->name('menu');
        
        // banner
        $router->get('/banner', 'PageController@banner')->name('banner');
        $router->post('/banner', 'PageController@storeBanner')->name('store_banner');

        // about page
        $router->get('/about', 'SettingController@about')->name('about-page');
        $router->post('/about', 'SettingController@storeAbout');
    });

    /* tags */
    $router->group(['prefix' => 'tags', 'as' => 'tags.'], function() use($router) {
        $router->get('/', 'TagController@list')->name('index');
    });

    /* Media */
    $router->group(['prefix' => 'media', 'as' => 'media.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'MediaController@index')->name('index');
        $router->post('/', 'MediaController@store')->name('store');
    });

    /* Employyers */
    $router->group(['prefix' => 'emplyees', 'as' => 'employees.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'EmployeeController@index')->name('index');
    });
    
    // Blog
    $router->group(['prefix' => '/channels', 'as' => 'channels.', 'middleware' => 'role:content-manager'], function() use($router){
        $router->get('/', 'ChannelController@index')->name('index');

        $router->group(['prefix' => '/{id}', 'as' => 'threads.'],function() use($router){
            $router->get('/threads', 'ThreadsController@index')->name('index');
            $router->get('/threads/create', 'ThreadsController@create')->name('create');
            $router->post('/threads', 'ThreadsController@store')->name('store');
            $router->get('/threads/{thread}/seo', 'ThreadsController@seo')->name('seo');
            $router->patch('/threads/{thread}/seo', 'ThreadsController@storeSeo');
            $router->get('/threads/{thread}/edit', 'ThreadsController@edit')->name('edit');
            $router->get('/threads/{thread}/replies', 'ThreadsController@replies')->name('replies');
            $router->put('/threads/{thread}', 'ThreadsController@update')->name('update');
        });
    });

    $router->get('/replies', 'ReplyController@index')->name('replies');
    $router->post('/replies/{reply}', 'ReplyController@store')->name('replies.store');
    $router->delete('/replies/{reply}', 'ReplyController@destroy')->name('replies.delete');

    // Users
    $router->resource('/users', 'UserController')->names([

app/Models/Channels.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Channels extends Model
{
   protected $fillable = [
      'name',
      'slug',
      'lang'
   ];

   public function getRouteKeyName()
   {
      return 'slug';
   }

   public function threads()
   {
      return $this->hasMany(Threads::class);
   }
}

app/Http/Controllers/Admin/ChannelController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Channels;
use App\Http\Resources\ChannelsResource;
use App\Http\Controllers\Controller;

class ChannelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
        return view('admin.channels.index');
    }

    public function list(Request $request){
        $query = Channels::orderBy('id', 'desc');

        if($request->lang)
            $query->where('lang', strtoupper($request->lang));
        
        $channels = $query->get();

        return ChannelsResource::collection($channels);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  =>  'required',
            'lang'  =>  'required|in:fa,en,ar'
        ]);

        $channel = Channels::create([
            'name'  =>  $request->name,
            'slug'  =>  preg_replace('/\s/', '-', $request->name),
            'lang'  =>  strtoupper($request->lang)
        ]);

        return new ChannelsResource($channel);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'  =>  'required',
            'lang'  =>  'required|in:fa,en,ar'
        ]);

        Channels::where('id', $id)->update([
            'name'  =>  $request->name,
            'slug'  =>  preg_replace('/\s/', '-', $request->name),
            'lang'  =>  strtolower($request->lang)
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Channels::where('id', $id)
            ->delete();
    }
}

resources/views/admin/channels/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
    {{ Breadcrumbs::render('channels') }}
    </div>
    
    <div id="channels_container" class="container"></div>
@endsection

@push('js')
    <script src="{{ mix('assets/js/admin/channels.js') }}"></script>
@endpush

resources/views/admin/channels/replies.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
    {{ Breadcrumbs::render('channels') }}
    </div>
    
    <div class="container">
        <div class="accordion">
        @foreach ($replies as $item)
        <div class="card mb-3">
            <div class="card-header text-right">
                <a href="{{ route('threads-show', ['channel'  =>  $item->thread->channel_id, 'thread' => $item->thread->id]) }}" target="_blank">{{ $item->thread->title }}</a>

                <button type="button" class="btn btn-sm btn-outline-info float-left" data-toggle="collapse" href="#collapse-{{ $item->id }}" role="button" aria-expanded="false" aria-controls="collapseExample">
                    <i class="fa fa-reply"></i>
                </button>
            </div>

            <div class="collapse" id="collapse-{{ $item->id }}">
                <form action="{{ route('admin.replies.store', ['reply' => $item->id]) }}" method="POST" class="py-3">
                    @csrf

                    <div class="col-12 text-right">
                        <div class="form-group">
                            <label for="">پاسخ شما</label>
                            <textarea name="body" class="form-control"></textarea>
                        </div>
                    </div>

                    <div class="col-12">
                        <button type="submit" class="btn btn-sm btn-outline-primary">ذخیره</button>
                    </div>
                </form>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <ul class="form-group text-right pr-0">
                            <li class="list-group-item">نام: {{ $item->name }}</li>
                            <li class="list-group-item">ایمیل: {{ $item->email }}</li>
                        </ul>
                    </div>

                    <div class="col-6 text-justify">
                        {!! $item->body !!}
                    </div>
                </div>
            </div>

            <div class="card-footer">
                <div class="row">
                    <div class="col-6 text-right">
                        زمان ثبت نظر:  {{ $item->created_at->diffForHumans() }}
                    </div>

                    <div class="col-6">
                        <form action="{{ route('admin.replies.delete', ['reply' => $item->id]) }}" method="POST" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-outline-danger">
                                <i class="fa fa-trash-alt"></i>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
        </div>

        {{ $replies->links() }}
    </div>
@endsection