routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localize', 'localizationRedirect']], function () use($router) {
    $router->get('/', 'PageController@index')->name('/');
    $router->get('/about', 'PageController@about')->name('about');
    $router->get('/contact-us', 'PageController@contactus')->name('contactus');
    $router->get('/teamus', 'PageController@teams')->name('team');
    $router->get('/search', 'PageController@search')->name('search');

    $router->group(['prefix' => '/services', 'as' => 'services.'], function() use($router) {
        $router->get('/', 'ServiceController@index')->name('index');
        $router->get('/{name}', 'ServiceController@show')->name('show');
    });

    // Posts
    $router->get('/threads', 'ThreadController@index')->name('threads-list');
    $router->get('/threads/{thread}', 'ThreadController@show')->name('thread-show');
    $router->get('/threads/{channel}','ThreadController@index')->name('threads-channel');
    $router->get('/threads/{channel}/{thread}','ThreadController@show')->name('threads-show');
    $router->post('/threads/{thread}/reply', 'ReplyController@store')->name('reply.create');

    // news
    $router->resource('/news', 'NewsController')->only(['index', 'show'])
        ->names([
            'index' =>  'news.index',
            'show'  =>  'news.show'
        ]);

    // Treatments
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/{treatment}', 'TreatmentController@show')->name('show');
        $router->post('/{id}/advice', 'TreatmentController@store_request')->name('advice-request');
    });

    // Conditions
    $router->group(['prefix' => '/conditions', 'as' => 'conditions.'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        $router->get('/{condition}', 'ConditionController@show')->name('show');
    });

    // Doctors
    $router->group(['prefix' => '/doctors', 'as' => 'teams.'], function() use($router) {
        $router->get('/', 'TeamController@index')->name('index');
        $router->get('/{name}', 'TeamController@show')->name('show');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/* start admin routes */
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'role:operator|admin'], 'as' => 'admin.'], function() use($router){
    $router->get('/', 'PanelController@panel')->name('panel');

    $router->resource('/users-opinions', 'UsersOpinionController');

    /* Departments */
    $router->group(['prefix' => '/departments', 'as' => 'departments.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'DepartmentController@index')->name('index');
    });

    /* Services */
    $router->group(['prefix' => 'services-categories', 'as' => 'services-categories.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'ServiceCategoryController@index')->name('index');
        $router->get('/{id}/edit', 'ServiceCategoryController@edit')->name('edit');
        $router->put('/{id}', 'ServiceCategoryController@update')->name('update');
    });

    /* conditions */
    $router->group(['prefix' => 'conditions', 'as' => 'conditions.', 'middleware' => 'role:conditions-manager'], function() use($router) {
        $router->get('/', 'ConditionController@index')->name('index');
        
        $router->group(['prefix' => '/{id}'], function() use($router){
            $router->put('', 'ConditionController@update')->name('update');
            $router->get('/edit', 'ConditionController@edit')->name('edit');
            $router->get('/faq', 'ConditionController@faq')->name('faq');
            $router->get('/seo', 'ConditionController@seo')->name('seo');
            $router->patch('/seo', 'ConditionController@storeSeo');
        });
    });
    
    /* treatments */
    $router->group(['prefix' => '/treatments', 'as' => 'treatments.', 'middleware' => 'role:treatments-manager'], function() use($router) {
        $router->get('/', 'TreatmentController@index')->name('index');
        $router->get('/treatment-requests', 'TreatmentController@requestList')->name('requests');
        
        $router->group(['prefix' => '/{id}'], function() use($router) {
            $router->put('/', 'TreatmentController@update')->name('update');
            $router->get('/edit', 'TreatmentController@edit')->name('edit');
            $router->get('/faq', 'TreatmentController@faq');
            $router->get('/seo', 'TreatmentController@seo')->name('seo');
            $router->patch('/seo', 'TreatmentController@storeSeo')->name('seo');
            $router->get('/requests', 'TreatmentController@adviseList');

            $router->group(['prefix' => '/comments', 'as' => 'comments.'], function() use($router) {
                $router->get('/', 'TreatmentController@fetchCommentsList')->name('index');
                $router->post('/', 'TreatmentController@storeComment')->name('store');
                $router->post('/{comment_id}/edit', 'TreatmentController@updateComment')->name('update');
                $router->get('/create', 'TreatmentController@createComment')->name('create');
                $router->get('/{comment_id}/edit', 'TreatmentController@editComment')->name('edit');
                $router->delete('{comment_id}', 'TreatmentController@destroyComment')->name('delete');
            });


            $router->get('/pricing', 'TreatmentController@pricing')->name('pricing');
        });
    });

    $router->group(['prefix' => '/news', 'as' => 'news.'], function() use($router) {
        $router->get('/', 'NewsController@index')->name('index');
        $router->get('/create', 'NewsController@create')->name('create');
        $router->post('/', 'NewsController@store')->name('store');
        $router->put('/{id}', 'NewsController@update')->name('update');
        $router->get('/{id}/edit', 'NewsController@edit')->name('edit');
        $router->delete('/{id}', 'NewsController@destroy')->name('delete');
    });

    /* Settings */
    $router->group(['prefix' => 'settings', 'as' => 'settings.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'SettingController@index')->name('index');
        $router->post('/', 'SettingController@store_setting')->name('store-setting');
        $router->get('/social', 'SettingController@social')->name('social');
        $router->post('/social', 'SettingController@store_social')->name('store-social');
        $router->get('/home_slider', 'PageController@home_main_slider')->name('home-main-slider');
        $router->post('/home_slider', 'PageController@store_main_slider')->name('store-main-slider');
        $router->put('/home_slider', 'PageController@update_main_slider')->name('update-main-slider');
        
        $router->get('/welcome', 'PageController@welcome_page')->name('welcome-page');
        
        // menu
        $router->get('/menu', 'PageController@menu')->name('menu');
        
        // banner
        $router->get('/banner', 'PageController@banner')->name('banner');
        $router->post('/banner', 'PageController@storeBanner')->name('store_banner');

        // about page
        $router->get('/about', 'SettingController@about')->name('about-page');
        $router->post('/about', 'SettingController@storeAbout');
    });

    /* tags */
    $router->group(['prefix' => 'tags', 'as' => 'tags.'], function() use($router) {
        $router->get('/', 'TagController@list')->name('index');
    });

    /* Media */
    $router->group(['prefix' => 'media', 'as' => 'media.', 'middleware' => 'role:content-manager'], function() use($router) {
        $router->get('/', 'MediaController@index')->name('index');
        $router->post('/', 'MediaController@store')->name('store');
    });

    /* Employyers */
    $router->group(['prefix' => 'emplyees', 'as' => 'employees.', 'middleware' => 'role:clinic-manager'], function() use($router) {
        $router->get('/', 'EmployeeController@index')->name('index');
    });
    
    // Blog
    $router->group(['prefix' => '/channels', 'as' => 'channels.', 'middleware' => 'role:content-manager'], function() use($router){
        $router->get('/', 'ChannelController@index')->name('index');

        $router->group(['prefix' => '/{id}', 'as' => 'threads.'],function() use($router){
            $router->get('/threads', 'ThreadsController@index')->name('index');
            $router->get('/threads/create', 'ThreadsController@create')->name('create');
            $router->post('/threads', 'ThreadsController@store')->name('store');
            $router->get('/threads/{thread}/seo', 'ThreadsController@seo')->name('seo');
            $router->patch('/threads/{thread}/seo', 'ThreadsController@storeSeo');
            $router->get('/threads/{thread}/edit', 'ThreadsController@edit')->name('edit');
            $router->get('/threads/{thread}/replies', 'ThreadsController@replies')->name('replies');
            $router->put('/threads/{thread}', 'ThreadsController@update')->name('update');
        });
    });

    $router->get('/replies', 'ReplyController@index')->name('replies');
    $router->post('/replies/{reply}', 'ReplyController@store')->name('replies.store');
    $router->delete('/replies/{reply}', 'ReplyController@destroy')->name('replies.delete');

    // Users
    $router->resource('/users', 'UserController')->names([

app/Models/UsersOpinions.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UsersOpinions extends Model
{
    protected $fillable = [
        'lang',
        'name',
        'body'
    ];

    public function getLanguageAttribute() {
        switch($this->lang) {
            case 'FA':
                return 'فارسی';
            break;
            case 'EN':
                return 'انگلیسی';
            break;
            case 'AR':
                return 'عربی';
            break;
        }
    }
}

app/Http/Controllers/Admin/UsersOpinionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\UsersOpinions;
use App\Http\Controllers\Controller;

class UsersOpinionController extends Controller
{
    public function index() {
        $opinions = UsersOpinions::orderBy('id', 'desc')->paginate(25);

        return view('admin.users-opinions.index', compact('opinions'));
    }

    public function create() {
        return view('admin.users-opinions.create');
    }

    public function store(Request $request) {
        $this->validate($request, [
            'lang'  =>  'required|in:FA,EN,AR',
            'name'  =>  'required',
            'body'   =>  'required'
        ]);

        UsersOpinions::create([
            'lang'  =>  $request->lang,
            'name'  =>  $request->name,
            'body'   =>  $request->body
        ]);

        return back()->with('success', 'اطلاعات با موفقیت ذخیره گردید');
    }

    public function edit($id) {
        $opinion = UsersOpinions::where('id', $id)->first();

        return view('admin.users-opinions.edit', compact('opinion'));
    }

    public function update(Request $request, $id) {
        $this->validate($request, [
            'lang'  =>  'required|in:FA,EN,AR',
            'name'  =>  'required',
            'body'   =>  'required'
        ]);

        UsersOpinions::where('id', $id)->update([
            'lang'  =>  $request->lang,
            'name'  =>  $request->name,
            'body'  =>  $request->body
        ]);

        return redirect()->route('admin.users-opinions.index')->with('success', 'طلاعات با موفقیت ذخیره گردید');
    }

    public function destroy($id) {
        UsersOpinions::where('id', $id)->delete();

        return back()->with('success', 'نظر کاربر حذف گردید');
    }
}

resources/views/admin/users-opinions/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        {{ Breadcrumbs::render('admin-users-opinions-create') }}
    </div>

    <div class="container">
      <div class="card">
        <div class="card-body text-right">
          <div class="container">
            <form method="post" class="row" action="{{ route('admin.users-opinions.store') }}">
              @csrf

              <div class="col-md-6">
                <div>
                  <label for="">زبان</label>
                  <select name="lang" class="form-control" id="" required>
                    <option value="">انتخاب کنید</option>
                    <option value="FA">فارسی</option>
                    <option value="EN">انگلیسی</option>
                    <option value="AR">عربی</option>
                  </select>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label for="">نام</label>
                  <input type="text" name="name" class="form-control" required value="{{ old('name') }}" />
                </div>
              </div>

              <div class="col-12">
                <label for="">توضیحات</label>
                <textarea rows="5" class="form-control" name="body">{{ old('body') }}</textarea>
              </div>

              <div class="col-12 mt-3">
                <button type="submit" class="btn btn-success">ذخیره</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
@endsection

resources/views/admin/users-opinions/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        {{ Breadcrumbs::render('admin-users-opinions-create') }}
    </div>

    <div class="container">
      <div class="card">
        <div class="card-body text-right">
          <div class="container">
            <form method="post" class="row" action="{{ route('admin.users-opinions.update', ['id' => $opinion->id]) }}">
              @csrf
              @method('PUT')

              <div class="col-md-6">
                <div>
                  <label for="">زبان</label>
                  <select name="lang" class="form-control" id="" required>
                    <option value="">انتخاب کنید</option>
                    <option value="FA" {{ $opinion->lang == 'FA' ? 'selected' : '' }} >فارسی</option>
                    <option value="EN" {{ $opinion->lang == 'EN' ? 'selected' : '' }}>انگلیسی</option>
                    <option value="AR" {{ $opinion->lang == 'AR' ? 'selected' : '' }}>عربی</option>
                  </select>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label for="">نام</label>
                  <input type="text" name="name" class="form-control" required value="{{ $opinion->name }}" />
                </div>
              </div>

              <div class="col-12">
                <label for="">توضیحات</label>
                <textarea rows="5" class="form-control" name="body">{{ $opinion->body }}</textarea>
              </div>

              <div class="col-12 mt-3">
                <button type="submit" class="btn btn-success">ذخیره</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
@endsection

resources/views/admin/users-opinions/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        {{ Breadcrumbs::render('admin-users-opinions') }}
    </div>

    <div class="container">
      
      <div class="card">
        <div class="card-header text-right">
          لیست نظرات
          <a class="btn btn-primary float-left" href="{{ route('admin.users-opinions.create') }}">افزودن نظر جدید</a>
        </div>
        <div class="card-body text-right">
          <div class="container">
            @if($opinions->count())
            <table class="table table-striped thead-dark">
              <thead>
                <tr>
                  <th>#</th>
                  <th>نام</th>
                  <th>زبان</th>
                  <th>توضیحات</th>
                  <th></th>
                </tr>
              </thead>
      
              <tbody>
                @foreach ($opinions as $item)
                <tr>
                  <td>{{ fa_nums(++$loop->index) }}</td>
                  <td>{{ $item->name }}</td>
                  <td>{{ $item->language }}</td>
                  <td>{{ str_limit($item->body, 250) }}</td>
                  <td class="d-flex">
                    <a class="btn btn-sm btn-warning" href="{{ route('admin.users-opinions.edit', ['id' => $item->id]) }}">
                      ویرایش
                      <i class="fa fa-edit"></i>
                    </a>

                    <form method="POST" action="{{ route('admin.users-opinions.destroy', ['id' => $item->id]) }}" class="mr-2">
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger" type="submit">
                        حذف
                        <i class="fa fa-trash-alt"></i>
                      </button>
                    </form>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>

            <div class="mt-3">
              {{ $opinions->links() }}
            </div>
            @else
              <div class="alert alert-info">
                اطلاعاتی ثبت نشده است
              </div>
            @endif
          </div>
        </div>
      </div>
    </div>
@endsection